#!/bin/bash

MYDIR=$(dirname $0)
cd $MYDIR
source default_conf

set -e

[ -z "$DEFAULT_USER" ] && DEFAULT_USER=vini
[ -z "$DEFAULT_TIMEZONE" ] && DEFAULT_TIMEZONE="America/Sao_Paulo"
[ -z "$LOCAL_TIME" ] && LOCAL_TIME=/usr/share/zoneinfo/"$DEFAULT_TIMEZONE"
[ -z "$HOSTNAME" ] && HOSTNAME=alinux01

PKGLIST="$(cat list.txt)"
pacman --needed -Syu --noconfirm $PKGLIST
systemctl enable kdm
#hostnamectl set-hostname $HOSTNAME
echo "$HOSTNAME" > /etc/hostname
set +e
systemctl enable vboxservice
systemctl enable sshd.service

find /var/cache/pkgfile/core.files -mtime -30 | read || pkgfile --update

gpasswd -a "$DEFAULT_USER" vboxsf

grep -q ^vboxguest /etc/modules-load.d/virtualbox.conf 2>/dev/null && {
echo "vboxguest
vboxsf
vboxvideo
" >> /etc/modules-load.d/virtualbox.conf
}


grep -q '^LANG=' /etc/locale.conf 2>/dev/null || echo 'LANG="en_US.UTF-8"' >> /etc/locale.conf

grep -q ^en_US.UTF-8 /etc/locale.gen 2>/dev/null || {
echo en_US.UTF-8 UTF-8   >> /etc/locale.gen
locale-gen
}


[ -f "$LOCAL_TIME" ] && ln -sf "$LOCAL_TIME" /etc/localtime
echo " ======================================== "
echo "Add autodefrag and compress=zlib to /etc/fstab if you're using btrfs"

